[project]
name = "pearl-ctf-1e3f5a2d-7c8b-4e9a-f1d6-c2b5a8e3f9d1"
version = "0.0.0"
requires-python = ">=3.14.0"
dependencies = [
  "gensim>=4.4.0",
  "numpy>=2.5.0",
  "opencv-python>=4.13.0",
  "sympy>=1.14.0",
]

[tool.uv]
add-bounds = "exact"
exclude-newer = "P5D"
package = false
required-version = ">=0.11.0"
